version: '2'
services:
  web:
    build: .
    environment:
      - 'NODE_CONFIG={"database": {"data": {"host": "mongo"}, "session": {"host": "redis" }}}'
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    depends_on: 
      - mongo
      - redis
  mongo:
    image: mongo
    restart: unless-stopped
    command: --smallfiles
    volumes:
      - ./data/mongo:/data/mongo
  redis:
    image: redis
    restart: unless-stopped
    volumes:
      - ./data/redis:/data/redis
